- name: CentOS 7 Zabbix-agent install
  hosts: all
  tasks:
    - name: Zabbix Repository
      yum:
        name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
        state: present
    - name: Installs Zabbix-agent
      yum: pkg={{ item }}
      with_items:
        - zabbix
        - zabbix-agent
