- name: CentOS 7 Zabbix-agent install
  hosts: all
  tasks:
    - name: Zabbix Repository
      yum_repository:
        name: zabbix
        description: Zabbix Official Repository - $basearch
        disable_gpg_check: yes
        baseurl: http://repo.zabbix.com/zabbix/3.4/rhel/{{ distribution_major_version | default(ansible_distribution_major_version) }}/$basearch/
    - name: Installs Zabbix-agent
      yum: pkg=zabbix-agent
