- name: CentOS 7 Zabbix-agent install
  hosts: all
  tasks:
    - name: Zabbix Repository
      yum_repository:
        name: zabbix
        description: Zabbix Official Repository - $basearch
        baseurl: http://repo.zabbix.com/zabbix/3.4/rhel/{{ ansible_distribution_major_version }}/$basearch/
    - name: Installs Zabbix-agent
      yum: pkg=zabbix-agent
