- name: CentOS Zabbix-agent install
  hosts: all
  tasks:
    - name: Zabbix Repository key ZABBIX
      get_url:
        url: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Zabbix Repository key ZABBIX-A14FE591
      get_url:
        url: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Zabbix Official Repository
      yum_repository:
        name: zabbix
        description: Zabbix Official Repository
        baseurl: http://repo.zabbix.com/zabbix/3.4/rhel/{{ distribution_major_version | default(ansible_distribution_major_version) }}/$basearch/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591
    - name: Zabbix Official Repository deprecated
      yum_repository:
        name: zabbix-deprecated
        description: Zabbix Official Repository
        baseurl: http://repo.zabbix.com/zabbix/3.4/rhel/{{ distribution_major_version | default(ansible_distribution_major_version) }}/$basearch/deprecated
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591
     - name: Zabbix Official Repository deprecated
      yum_repository:
        name: zabbix-non-supported
        description: Zabbix Official Repository non-supported
        baseurl: http://repo.zabbix.com/rhel/{{ distribution_major_version | default(ansible_distribution_major_version) }}/$basearch/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    - name: Installs Zabbix-agent
      yum: pkg=zabbix-agent
