- name: CentOS 7 Zabbix-agent install
  hosts: all
  tasks:
    - name: Zabbix Repository
      yum:
        name: http://repo.zabbix.com/zabbix/3.4/rhel/{{ansible_distribution_major_version}}/x86_64/zabbix-release-3.4-1.el{{ansible_distribution_major_version}}.noarch.rpm.rpm
        update_cache: yes
        state: present
    - name: Installs Zabbix-agent
      yum: pkg=zabbix-agent
